config/routes.rb
Rails.application.routes.draw do
  resources :books

  root to: redirect('/books')

  get '/books/:id/same_author', to: 'books#same_author', as: 'same_author'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	GENRES = [
		'Science fiction',
    'Drama',
    'Action and Adventure',
    'Romance',
    'Mystery',
    'Horror',
    'Fantasy',
    'Novel'
	]

  validates :title, presence: true
  validates :genre, presence: true, inclusion: GENRES
  validates :publish_date, presence: true
  validates :isbn, presence: true, isbn_format: true, if: :released_1967_or_later

  before_save :titleize_title

  private

    def released_1967_or_later
      publish_date && publish_date > Date.parse('1 Jan 1967')
    end

    def titleize_title
      return nil if !title.present?
      
      self.title = title.gsub(/\w+/, &:capitalize).gsub(/\s+/, ' ')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def index
		if !params.key?(:genres)
			params[:genres] = {}
		end

		permitted = params.permit(:sort, genres: params[:genres].keys)
		sort = permitted[:sort] || session[:sort]

		case sort
			when 'title'
				ordering, @title_header = {:title => :asc}, 'hilite'
			when 'publish_date'      
				ordering, @publish_date_header = {:publish_date => :asc}, 'hilite'
		end
 
		@selected_genres = permitted[:genres] || session[:genres] || {}
		if @selected_genres == {}  
			@selected_genres = Hash[Book::GENRES.map {|genre| [genre, genre]}]
		end

		if permitted[:sort] != session[:sort] or permitted[:genres] != session[:genres]
			session[:sort] = sort
			session[:genres] = @selected_genres
			redirect_to :sort => sort, :genres => @selected_genres and return
		end

		@books = Book.where(genre: @selected_genres.keys).order(ordering)
	end

	def show
		id = params[:id]
		@book = Book.find(id)
	end

	def new
		@book = Book.new
	end

	def create
		params.require(:book)
		permitted = params[:book].permit(:title, :genre, :isbn, :publish_date, :description, :genres, :author)
		
		@book = Book.new(permitted)

		if @book.save
			flash[:notice] = "#{@book.title} was successfully created."

			redirect_to books_path
		else
			render 'new'
		end
	end

	def edit
		@book = Book.find params[:id]
	end

	def update
		@book = Book.find params[:id]
		
		params.require(:book)
		params.require(:book)
		permitted = params[:book].permit(:title, :genre, :isbn, :publish_date, :description, :genres, :author)
		
		if @book.update(permitted)
			flash[:notice] = "#{@book.title} was successfully updated."

			redirect_to books_path(@book)
		else
    	render 'edit'
  	end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy

		flash[:notice] = "Book '#{@book.title}' deleted."

		redirect_to books_path
	end

	def same_author
		@book = Book.find(params[:id])
		if !@book.author.present?
			return redirect_to books_path, :alert => "'#{@book.title}' has no author info"
		end
			@books = Book.where(author: @book.author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book_form.html.haml
- unless @book.errors.empty?
	Failed to #{controller.action_name} book:
	%ul
		- @book.errors.full_messages.each do |error|
			%li= error

= label :book, :title, 'Title:'
= text_field :book, :title

= label :book, :author, 'Author:'
= text_field :book, :author

= label :book, :genre, 'Genre:'
= select :book, :genre, Book::GENRES

= label :book, :isbn, 'ISBN Number:'
= text_field :book, :isbn

= label :book, :publish_date, 'Publishing Date:'
= date_select :book, :publish_date, {:start_year => 1900, :end_year => Date.today.year}
= label :book, :description, 'Description'
= text_area :book, :description, size: "30x10"

app/views/books/_book_table.html.haml
%table#books
	%thead
		%tr
			%th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title'), :id => 'title_header'
			%th Author
			%th Genre
			%th ISBN number
			%th{:class => @publish_date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date'), :id => 'publish_date_header'
			%th More Info
	%tbody
	- @books.each do |book|
		%tr
			%td= book.title
			%td= book.author
			%td= book.genre
			%td= book.isbn
			%td= book.publish_date.strftime("%d-%m-%Y")
			%td= link_to "More about #{book.title}", book_path(book)

app/views/books/edit.html.haml
%h2 Edit "#{@book.title}"

= form_tag book_path(@book), :method => :put do
	= render :partial => 'book_form'
	= submit_tag 'Update Book Info'

app/views/books/index.html.haml
%h1 My Books

%br
= form_tag books_path, :method => :get, :id => 'genres_form' do
	= hidden_field_tag "title_sort", true if @title_header
	= hidden_field_tag ":publish_date", true if @date_header
	Include:
	- Book::GENRES.each do |genre|
		= genre
		= check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
	= submit_tag 'Refresh', :id => 'genres_submit'
%br

= render 'book_table'

= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

=form_tag books_path, :method => :post do
	= render :partial => 'book_form'
	= submit_tag 'Save Changes'

app/views/books/same_author.html.haml
%h1 "Books from same #{@book.author}"

%br
= render 'book_table'

= link_to 'Back to all book list', books_path

app/views/books/show.html.haml
%h2 Details about #{@book.title}

%ul#details
	%li
		Author:
		= @book.author

	%li 
		Genre:
		= @book.genre

	%li
		ISBN number:
		= @book.isbn

	%li
		Publishing date:
		= @book.publish_date.strftime("%B %d, %Y")

%h3 Description:
%p#description= @book.description

= link_to 'Find Books With Same Author', same_author_path(@book)
%br
= link_to 'Edit info', edit_book_path(@book)
%br
= link_to 'Delete', book_path(@book), :method => :delete
%br
= link_to 'Back to book list', books_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title My Favourite Books
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags

  %body
    #main
      -if flash[:notice]
        #notice.message= flash[:notice]
      -elsif flash[:alert]
        #warning.message= flash[:alert]
      = yield